### ISSUE TITLE
Switch to `tracing`

### ISSUE THREAD

**Issue by elpiel** [embassy-rs/teleprobe#3]
`probe-rs` uses the `tracing` crate and we cannot control the logging level when calling `teleprobe` with `RUST_LOG`.
Any tracing information emitted by `probe-rs` is not visible.

**Comment by Dirbaio** [comment]
It was a bug in the custom logger, https://github.com/embassy-rs/teleprobe/commit/525ecb582062972ba9b6c6745b8595d719b0a517 fixes it.
