### ISSUE TITLE
How to install teleprobe? And why not probe-rs?

### ISSUE THREAD

**Issue by overheat** [embassy-rs/teleprobe#5]
I saw teleprobe used in `embassy/tests`, but I got this error, after `cd embassy/tests/rp & cargo run --bin float`

```
error: could not execute process `teleprobe local run --chip RP2040 --elf target/thumbv6m-none-eabi/debug/float` (never executed)
```

**Comment by elpiel** [comment]
Because this crate is not published on crates.io you must install it from the git repo (https://doc.rust-lang.org/cargo/commands/cargo-install.html):
`cargo install --git https://github.com/embassy-rs/teleprobe teleprobe`
